[package]
name = "smartcropper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.18"
image = "0.24.8"

[dev-dependencies]
image-compare = "0.3.1"
